import type { Metadata } from "next";
import { Kalnia } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import ScrollToTop from "@/ScrollToTop";
import Footer from "./components/Footer";
import classNames from "classnames";

const kalnia = Kalnia({
  subsets: ["latin"],
  variable: "--font-kalnia",
});

export const metadata: Metadata = {
  title: "Elevated Events",
  description: "Generated by create next app",
  keywords:
    "Felicia Cook, Elevated Events, Event Planner, Event Planning Services, Event Management, Event Coordination, Professional Event Planner, Event Planning Company, Wedding Planner, Corporate Event Planner, Birthday Party Planner, Conference Planning, Trade Show Organizer, Concert Event Planning, Festival Organizer, Gala Event Planning, Charity Event Planning, Private Event Planning, Huntsville Event Planner, Birmingham Event Planner, Alabama Event Planner, Huntsville Wedding Planner, Birmingham Wedding Planner, Alabama Wedding Planner, Event Planning in Huntsville, Event Planning in Birmingham, Event Planning in Alabama, Huntsville Corporate Event Planning, Birmingham Corporate Event Planning, Alabama Corporate Event Planning, Full-Service Event Planning, Custom Event Planning, Event Design Services, Event Decor Services, Luxury Event Planning, Budget-Friendly Event Planning, Eco-Friendly Event Planning, Destination Event Planning, Stress-Free Event Planning, Affordable Event Planning, Last-Minute Event Planner, Seamless Event Management, How to Plan a Corporate Event, Best Event Planners in Huntsville, Best Event Planners in Birmingham, Best Event Planners in Alabama, Event Planning Tips and Tricks, Affordable Wedding Planners Near Me, Event Planning Checklist, Holiday Party Planner, Summer Event Planning, Winter Wedding Planning, Back-to-School Event Planning",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={classNames(
          kalnia.variable,
          "max-w-[1502px] mx-auto bg-amber-300 min-h-[100vh]"
        )}>
        <ScrollToTop />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
