import type { Metadata } from "next";
import { Kalnia } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const kalnia = Kalnia({ 
  subsets: ["latin"], 
  variable: '--font-kalnia'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={kalnia.variable}>
      <Navbar />
      {children}</body>
    </html>
  );
}
