import type { Metadata } from "next";
import { Kalnia } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import ScrollToTop from "@/ScrollToTop";
import Footer from "./components/Footer";

const kalnia = Kalnia({ 
  subsets: ["latin"], 
  variable: '--font-kalnia'
});

export const metadata: Metadata = {
  title: "Elevated Events",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={kalnia.variable}>
        <ScrollToTop />
      <Navbar />
      {children}
      <Footer />
      </body>
    </html>
  );
}
